/*
 * This code is generated by blanco Framework.
 */
package dapanda.api.core.blanco.db.common.exception;

import java.sql.SQLException;

/**
 * Exception class for database constraint violation <br>
 * This class is used in the source code generated by blancoDb <br>
 * Note: This class will be used as a file after automatic source code generation.
 * @since 2005.05.12
 * @author blanco Framework
 */
public class IntegrityConstraintException extends SQLException {
    /**
     * SQLState code that represents this class.
     */
    protected static final String SQLSTATE_INTEGRITYCONSTRAINT = "23000";

    /**
     * Creates an instance of the exception object to indicate that a constraint violation has occurred.
     *
     * @deprecated Please do not use this constructor as much as possible, but use another constructor that can use the SQLState of the original exception and venderCode.
     */
    public IntegrityConstraintException() {
        super("Integrity consrtraint exception has occured.", SQLSTATE_INTEGRITYCONSTRAINT);
    }

    /**
     * Creates an instance of the exception object to indicate that a constraint violation has occurred.
     *
     * @deprecated Please do not use this constructor as much as possible, but use another constructor that can use the SQLState of the original exception and venderCode.
     *
     * @param reason Description of the exception
     */
    public IntegrityConstraintException(final String reason) {
        super(reason, SQLSTATE_INTEGRITYCONSTRAINT);
    }

    /**
     * Creates an instance of the exception object to indicate that a constraint violation has occurred.
     *
     * @deprecated Please do not use this constructor as much as possible, but use another constructor that can use the SQLState of the original exception and venderCode.
     *
     * @param reason Description of the exception
     * @param SQLState XOPEN code or SQL 99 code that identifies the exception
     */
    public IntegrityConstraintException(final String reason, final String SQLState) {
        super(reason, SQLState);
    }

    /**
     * Creates an instance of the exception object to indicate that a constraint violation has occurred.
     *
     * @param reason Description of the exception
     * @param SQLState XOPEN code or SQL 99 code that identifies the exception
     * @param vendorCode Specific exception codes defined by the database vendor
     */
    public IntegrityConstraintException(final String reason, final String SQLState, final int vendorCode) {
        super(reason, SQLState, vendorCode);
    }
}
