/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco

import blanco.restgenerator.valueobject.ApiGetTelegram
import io.micronaut.core.annotation.Introspected

/** 認可トークン確認用APIの応答電文です。 */
@Introspected class CheckTokenApiGetResponse : ApiGetTelegram()
