/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco

import blanco.restgenerator.valueobject.ApiGetTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.http.annotation.QueryValue
import javax.validation.Valid
import javax.validation.constraints.NotBlank

/** 認可トークン確認用APIの要求電文です。 */
@Introspected
data class CheckTokenApiGetRequest
    constructor(
        /** 認証シーケンスサーバが発行した認可トークン */
        @field:Valid @field:NotBlank @field:QueryValue var token: String?
    ) : ApiGetTelegram()
