/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco

/*
import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.emulator.application.NgManagement
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpResponse
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.annotation.RequestBean

/** アプリケーションサーバへのLocation ヘッダを返すリダイレクトAPI&lt;br&gt; */
@Controller("/ng")
class NgController
constructor(
    /** The implementation class to be called by NgController. */
    var ngManagement: NgManagement
) {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param argHttpRequest validation前のリクエスト情報です
   * @param bean get parameter set as bean.
   * @return validation済みのレスポンス情報です
   */
  @Get("/{appServer}/{groupId}/{userId}")
  fun doGet(
      argHttpRequest: HttpRequest<CommonRequest<RequestHeader, NgGetRequest>>,
      @RequestBean bean: NgGetRequest
  ): HttpResponse<CommonResponse<ResponseHeader, NgGetResponse>> {
    /* Creates HttpCommonRequest with httpRequest as delegator. */
    /* At this stage, commonRequest is tentative.*/
    val httpCommonRequest =
        HttpCommonRequest<CommonRequest<RequestHeader, NgGetRequest>>(
            argHttpRequest, true, listOf(), null)

    val info = RequestHeader()
    val commonRequest: CommonRequest<RequestHeader, NgGetRequest> = CommonRequest(info, bean)

    /* Stores the commonRequest with its type determined */
    httpCommonRequest.commonRequest = commonRequest

    /* Performs preprocessing (validation, etc.) */
    ngManagement.prepare(httpCommonRequest)

    /* Passes HttpCommonRequest */
    val httpResponse = ngManagement.doGet(httpCommonRequest)

    /* Postprocessing */
    ngManagement.finish(httpResponse, httpCommonRequest)

    return httpResponse
  }
}

 */
