/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco

import blanco.restgenerator.valueobject.ApiGetTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.http.annotation.PathVariable

/** 認証に失敗するトークンを含んだヘッダを返すAPIの要求電文です。 */
@Introspected
data class NgGetRequest
    constructor(
        /** アプリケーションserverのホスト名 */
        @field:PathVariable var appServer: String,
        /** グループID */
        @field:PathVariable var groupId: String,
        /** ユーザーID */
        @field:PathVariable var userId: String
    ) : ApiGetTelegram()
