/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco

import blanco.restgenerator.valueobject.ApiPostTelegram
import io.micronaut.core.annotation.Introspected

/** ユーザー登録APIの応答電文 */
@Introspected class RegisterPostResponse : ApiPostTelegram()
