/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import dapanda.api.emulator.blanco.CheckTokenApiGetRequest
import dapanda.api.emulator.blanco.CheckTokenApiGetResponse
import io.micronaut.http.HttpResponse

/** アプリケーションサーバから認証シーケンスサーバに対して要求する認可トークン確認用APIです。 */
interface ICheckTokenApiManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, CheckTokenApiGetRequest>>
  ): HttpResponse<CommonResponse<CheckTokenApiGetResponse>>
}
