/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.emulator.blanco.LogoutPutRequest
import dapanda.api.emulator.blanco.LogoutPutResponse
import io.micronaut.http.HttpResponse

/** ログアウトAPI&lt;br&gt; */
interface ILogoutManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPut(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, LogoutPutRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, LogoutPutResponse>>
}
