/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import dapanda.api.emulator.blanco.LoginPostRequest
import dapanda.api.emulator.blanco.LoginPostResponse
import io.micronaut.http.HttpResponse

/** ログインAPI&lt;br&gt; */
interface ILoginManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, LoginPostRequest>>
  ): HttpResponse<CommonResponse<LoginPostResponse>>
}
