/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.emulator.blanco.OkGetRequest
import dapanda.api.emulator.blanco.OkGetResponse
import io.micronaut.http.HttpResponse

/** アプリケーションサーバへのLocation ヘッダを返すリダイレクトAPI&lt;br&gt; */
interface IOkManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, OkGetRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, OkGetResponse>>
}
