/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.emulator.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.emulator.blanco.RegisterPostRequest
import dapanda.api.emulator.blanco.RegisterPostResponse
import io.micronaut.http.HttpResponse

/** ユーザー登録API&lt;br&gt; */
interface IRegisterManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, RegisterPostRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, RegisterPostResponse>>
}
