/*
 * This code is generated by blanco Framework.
 */
package dapanda.api.core.blanco.db.common.util;

/**
 * A class that defines a dynamically generated ORDERBY clause.
 * This class is used in the source code generated by blancoDb.<br>
 * @since 2020.09.04
 * @author blanco Framework
 */
public class BlancoDbDynamicOrderBy {
    /**
     * Column name to use for sort order
     */
    private String column;

    /**
     * Specifies ascending or descending order.
     */
    private String order;

    /**
     * constructor
     */
    public BlancoDbDynamicOrderBy() {
    }

    /**
     * constructor
     *
     * @param argColumn Column name to use for sort order
     * @param argOrder Specifies ascending or descending order.
     */
    public BlancoDbDynamicOrderBy(final String argColumn, final String argOrder) {
        this.column = argColumn;
        this.order = argOrder;
    }

    /**
     * Column name to use for sort order
     *
     * @param argColumn Column name to use for sort order
     */
    public void setColumn(final String argColumn) {
        this.column = argColumn;
    }

    /**
     * Column name to use for sort order
     *
     * @return Column name to use for sort order
     */
    public String getColumn() {
        return this.column;
    }

    /**
     * Specifies ascending or descending order.
     *
     * @param argOrder Specifies ascending or descending order.
     */
    public void setOrder(final String argOrder) {
        this.order = argOrder;
    }

    /**
     * Specifies ascending or descending order.
     *
     * @return Specifies ascending or descending order.
     */
    public String getOrder() {
        return this.order;
    }
}
