/*
 * This code is generated by blanco Framework.
 */
package dapanda.api.core.blanco.db.common.util;

/**
 * A class that defines dynamically generated literals.
 * This class is used in the source code generated by blancoDb.<br>
 * @since 2021.05.19
 * @author blanco Framework
 */
public class BlancoDbDynamicLiteral {
    /**
     * Disables the set literal
     */
    private Boolean invalid = false;

    /**
     * constructor
     */
    public BlancoDbDynamicLiteral() {
    }

    /**
     * constructor
     *
     * @param argInvalid Disables the set literal
     */
    public BlancoDbDynamicLiteral(final Boolean argInvalid) {
        this.invalid = argInvalid;
    }

    /**
     * Disables the set literal
     *
     * @param argInvalid Disables the set literal
     */
    public void setInvalid(final Boolean argInvalid) {
        this.invalid = argInvalid;
    }

    /**
     * Disables the set literal
     *
     * @return Disables the set literal
     */
    public Boolean getInvalid() {
        return this.invalid;
    }
}
