/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.sample.blanco.SampleMethodTestDeleteRequest
import dapanda.api.sample.blanco.SampleMethodTestDeleteResponse
import dapanda.api.sample.blanco.SampleMethodTestGetRequest
import dapanda.api.sample.blanco.SampleMethodTestGetResponse
import dapanda.api.sample.blanco.SampleMethodTestPostRequest
import dapanda.api.sample.blanco.SampleMethodTestPostResponse
import dapanda.api.sample.blanco.SampleMethodTestPutRequest
import dapanda.api.sample.blanco.SampleMethodTestPutResponse
import io.micronaut.http.HttpResponse

/** Methodテスト用API&lt;br&gt; */
interface ISampleMethodTestManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, SampleMethodTestGetRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, SampleMethodTestGetResponse>>

  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, SampleMethodTestPostRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, SampleMethodTestPostResponse>>

  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPut(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, SampleMethodTestPutRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, SampleMethodTestPutResponse>>

  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doDelete(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, SampleMethodTestDeleteRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, SampleMethodTestDeleteResponse>>
}
