/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco.interfaces

import blanco.restgenerator.valueobject.HttpCommonRequest
import dapanda.api.sample.blanco.SamplePrimitiveArrayPayloadTestGetRequest
import dapanda.api.sample.blanco.SamplePrimitiveArrayPayloadTestPostRequest
import io.micronaut.http.HttpResponse

/** primitiveArrayPayloadテスト用API&lt;br&gt; */
interface ISamplePrimitiveArrayPayloadTestManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<SamplePrimitiveArrayPayloadTestGetRequest>
  ): HttpResponse<List<String>>

  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<SamplePrimitiveArrayPayloadTestPostRequest>
  ): HttpResponse<List<String>>
}
