/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco.interfaces

import blanco.restgenerator.valueobject.HttpCommonRequest
import dapanda.api.sample.blanco.SampleGetNoQueryGetRequest
import dapanda.api.sample.blanco.SampleGetNoQueryGetResponse
import io.micronaut.http.HttpResponse

/** パラメータなしGET API&lt;br&gt; */
interface ISampleGetNoQueryManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<SampleGetNoQueryGetRequest>
  ): HttpResponse<SampleGetNoQueryGetResponse>
}
