/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco.interfaces

import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.sample.blanco.SampleLoginPostRequest
import dapanda.api.sample.blanco.SampleLoginPostResponse
import io.micronaut.http.HttpResponse

/** ログインAPI&lt;br&gt; */
interface ISampleLoginManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<CommonRequest<RequestHeader, SampleLoginPostRequest>>
  ): HttpResponse<CommonResponse<ResponseHeader, SampleLoginPostResponse>>
}
