/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco.interfaces

import blanco.restgenerator.valueobject.HttpCommonRequest
import dapanda.api.sample.blanco.SampleArrayPayloadTestGetRequest
import dapanda.api.sample.blanco.SampleArrayPayloadTestGetResponse
import dapanda.api.sample.blanco.SampleArrayPayloadTestPostRequest
import dapanda.api.sample.blanco.SampleArrayPayloadTestPostResponse
import io.micronaut.http.HttpResponse

/** Methodテスト用API&lt;br&gt; */
interface ISampleArrayPayloadTestManagement {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doGet(
      httpRequest: HttpCommonRequest<SampleArrayPayloadTestGetRequest>
  ): HttpResponse<List<SampleArrayPayloadTestGetResponse>>

  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param httpRequest validation前のリクエスト情報です
   * @return validation済みのレスポンス情報です
   */
  fun doPost(
      httpRequest: HttpCommonRequest<SampleArrayPayloadTestPostRequest>
  ): HttpResponse<List<SampleArrayPayloadTestPostResponse>>
}
