/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPostTelegram
import io.micronaut.core.annotation.Introspected

/** POSTメソッドの応答電文 */
@Introspected class SampleMethodTestPostResponse : ApiPostTelegram()
