/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPostTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.serde.annotation.Serdeable
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size

/** ログインAPIの応答電文 */
@Introspected
@Serdeable
data class SampleLoginPostResponse
constructor(
    /**
     * トークン
     *
     * 規定値 [&quot;&quot;]
     */
    @field:Size(max = 64)
    @field:NotBlank
    @field:Pattern(regexp = "^[a-fA-F0-9]{32}$")
    @field:NotNull
    var token: String = ""
) : ApiPostTelegram()
