/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.util.BlancoRestGeneratorKtRequestDeserializer
import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.sample.application.SampleGetNoQueryManagement
import io.micronaut.core.annotation.Nullable
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpResponse
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.annotation.QueryValue

/** パラメータなしGET API&lt;br&gt; */
@Controller("/sample_query")
class SampleGetNoQueryController
constructor(
    /** The implementation class to be called by SampleGetNoQueryController. */
    var sampleGetNoQueryManagement: SampleGetNoQueryManagement
) {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param argHttpRequest validation前のリクエスト情報です
   * @param request Raw JSON set as queryString.
   * @return validation済みのレスポンス情報です
   */
  @Get
  fun doGet(
      argHttpRequest: HttpRequest<CommonRequest<RequestHeader, SampleGetNoQueryGetRequest>>,
      @Nullable @QueryValue request: String?
  ): HttpResponse<CommonResponse<ResponseHeader, SampleGetNoQueryGetResponse>> {
    /* Creates a CommonRequest instance from a JSON string. */
    val deserializer =
        BlancoRestGeneratorKtRequestDeserializer<RequestHeader, SampleGetNoQueryGetRequest>(
            CommonRequest::class.java)
    deserializer.infoClazz = RequestHeader::class.java
    deserializer.telegramClazz = SampleGetNoQueryGetRequest::class.java

    /* Creates HttpCommonRequest with httpRequest as delegator. */
    /* At this stage, commonRequest is tentative.*/
    val httpCommonRequest =
        HttpCommonRequest<CommonRequest<RequestHeader, SampleGetNoQueryGetRequest>>(
            argHttpRequest, true, listOf(), null)
    var myRequest = ""
    if (request == null) {
        myRequest = "{}"
    } else {
        myRequest = request
    }

    val commonRequest: CommonRequest<RequestHeader, SampleGetNoQueryGetRequest> =
        sampleGetNoQueryManagement.convertJsonToCommonRequest(
            myRequest, deserializer, httpCommonRequest)

    /* Stores the commonRequest with its type determined */
    httpCommonRequest.commonRequest = commonRequest

    /* Performs preprocessing (validation, etc.) */
    sampleGetNoQueryManagement.prepare(httpCommonRequest)

    /* Passes HttpCommonRequest */
    val httpResponse = sampleGetNoQueryManagement.doGet(httpCommonRequest)

    /* Postprocessing */
    sampleGetNoQueryManagement.finish(httpResponse, httpCommonRequest)

    return httpResponse
  }
}
