/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.util.BlancoRestGeneratorKtRequestDeserializer
import blanco.restgenerator.valueobject.CommonRequest
import blanco.restgenerator.valueobject.CommonResponse
import blanco.restgenerator.valueobject.HttpCommonRequest
import blanco.restgenerator.valueobject.RequestHeader
import blanco.restgenerator.valueobject.ResponseHeader
import dapanda.api.common.domain.model.authenticate.IAuthenticate
import dapanda.api.sample.application.SampleRegisterManagement
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpResponse
import io.micronaut.http.annotation.Body
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post
import jakarta.inject.Named

/** ユーザー登録API&lt;br&gt; */
@Controller("/sample_register")
class SampleRegisterController
constructor(
    /** The implementation class to be called by SampleRegisterController. */
    var sampleRegisterManagement: SampleRegisterManagement,
    @param:Named("SampleTokenAuthenticate")private val authenticate: IAuthenticate
) {
  /**
   * APIベースクラスから呼ばれる実行メソッドです
   *
   * @param argHttpRequest validation前のリクエスト情報です
   * @param argBody Raw JSON body.
   * @return validation済みのレスポンス情報です
   */
  @Post
  fun doPost(
      argHttpRequest: HttpRequest<CommonRequest<RequestHeader, SampleRegisterPostRequest>>,
      @Body argBody: String
  ): HttpResponse<CommonResponse<ResponseHeader, SampleRegisterPostResponse>> {
    /* Creates a CommonRequest instance from a JSON string. */
    val deserializer =
        BlancoRestGeneratorKtRequestDeserializer<RequestHeader, SampleRegisterPostRequest>(
            argHttpRequest.javaClass)
    deserializer.infoClazz = RequestHeader::class.java
    deserializer.telegramClazz = SampleRegisterPostRequest::class.java

    /* Creates HttpCommonRequest with httpRequest as delegator. */
    /* At this stage, commonRequest is tentative.*/
    val httpCommonRequest =
        HttpCommonRequest<CommonRequest<RequestHeader, SampleRegisterPostRequest>>(
            argHttpRequest, true, listOf(), null)

    val commonRequest: CommonRequest<RequestHeader, SampleRegisterPostRequest> =
        sampleRegisterManagement.convertJsonToCommonRequest(
            argBody, deserializer, httpCommonRequest)

    /* Stores the commonRequest with its type determined */
    httpCommonRequest.commonRequest = commonRequest

    /* Performs preprocessing (validation, etc.) */
    sampleRegisterManagement.prepare(httpCommonRequest, authenticate)

    /* Passes HttpCommonRequest */
    val httpResponse = sampleRegisterManagement.doPost(httpCommonRequest)

    /* Postprocessing */
    sampleRegisterManagement.finish(httpResponse, httpCommonRequest)

    return httpResponse
  }
}
