/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiGetTelegram
import io.micronaut.core.annotation.Introspected

/** ユーザー登録APIの応答電文 */
@Introspected class SampleGetNoQueryGetResponse : ApiGetTelegram()
