/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiDeleteTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.serde.annotation.Serdeable

/** DELETEメソッドの応答電文 */
@Introspected @Serdeable class SampleMethodTestDeleteResponse : ApiDeleteTelegram()
