/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPostTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.serde.annotation.Serdeable

/** POSTメソッドの応答電文 */
@Introspected @Serdeable class SamplePrimitiveArrayPayloadTestPostResponse : ApiPostTelegram()
