/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiGetTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.serde.annotation.Serdeable

/** ユーザー登録APIの応答電文 */
@Introspected @Serdeable class SampleGetNoQueryGetResponse : ApiGetTelegram()
