/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPutTelegram
import io.micronaut.core.annotation.Introspected

/** ログアウトAPIの応答電文 */
@Introspected class SampleLogoutPutResponse : ApiPutTelegram()
