/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPutTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.serde.annotation.Serdeable

/** ログアウトAPIの応答電文 */
@Introspected @Serdeable class SampleLogoutPutResponse : ApiPutTelegram()
