/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiDeleteTelegram
import io.micronaut.core.annotation.Introspected

/** DELETEメソッドの応答電文 */
@Introspected class SampleMethodTestDeleteResponse : ApiDeleteTelegram()
