/*
 * This source code has been generated by blanco Framework.
 */
package dapanda.api.sample.blanco

import blanco.restgenerator.valueobject.ApiPutTelegram
import io.micronaut.core.annotation.Introspected
import io.micronaut.core.annotation.Nullable
import io.micronaut.serde.annotation.Serdeable

/** POSTメソッドの応答電文 */
@Introspected
@Serdeable
data class SampleArrayPayloadTestPutResponse
constructor(
    /** ユーザ名っぽい何か */
    @Nullable var name: String,
    /** 年齢っぽい何か */
    @Nullable var age: Long
) : ApiPutTelegram()
